services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web

  web:
    image: registry.digitalocean.com/my-registry123/mydjangoapp:1.0.0
    restart: unless-stopped
    command: gunicorn mydjangoapp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
