services:
  nginx:
    image: nginx:1.28.0-alpine3.21
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_files:/app/staticfiles

  web:
    image: registry.digitalocean.com/my-registry123/mydjangoapp:1.0.0
    restart: unless-stopped
    command: gunicorn mydjangoapp.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - static_files:/app/staticfiles

volumes:
  static_files:
