version: '3'

services:
  user-service:
    image: registry.digitalocean.com/my-registry123/myspringapp-user-service:1.0.0
    env_file:
      - user-service.env
    ports:
      - "8081:8081"
    depends_on:
      - db
    networks:
      - spring-network

  product-service:
    image: registry.digitalocean.com/my-registry123/myspringapp-product-service:1.0.0
    env_file:
      - product-service.env
    ports:
      - "8082:8082"
    depends_on:
      - db
    networks:
      - spring-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring-network

networks:
  spring-network:
    driver: bridge

volumes:
  postgres_data:
