name: Deploy goapp app to k8s argocd

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-goapp-to-k8s-argocd.yml'
      - 'mygoapp/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Go Tests

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run Go tests
        working-directory: ./mygoapp
        run: |
          go mod tidy
          go test ./...

  build:
    runs-on: ubuntu-latest
    needs: test

    outputs:
      image_name: registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and push docker
        working-directory: ./mygoapp
        run: |
          docker build -t registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }} .
          docker login registry.digitalocean.com -u paulbundy07@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/mygoapp:${{ github.sha }}

  deploy1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'https://github.com/mirafzal/argocd-repo-lesson'
          token: '${{ secrets.ARGOCD_REPO_CHECKOUT_TOKEN }}'

      - name: Change deployment image tag
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.spec.template.spec.containers[0].image = "${{ needs.build.outputs.image_name }}"' 'helm-charts/myapp/deployment.yaml'

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          git add helm-charts/myapp/deployment.yaml
          git commit -m "Update image tag to ${{ needs.build.outputs.image_name }}" || echo "No changes to commit"
          git push origin HEAD:main
