name: Deploy spring product-service app with docker

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-spring-product-service-with-docker.yml'
      - 'myspringapp/product-service/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_name: registry.digitalocean.com/my-registry123/myspringapp-product-service:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and push docker
        working-directory: ./myspringapp/product-service
        run: |
          docker build -t registry.digitalocean.com/my-registry123/myspringapp-product-service:${{ github.sha }} .
          docker login registry.digitalocean.com -u paulbundy07@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/myspringapp-product-service:${{ github.sha }}
          
      

  deploy1:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./myspringapp/deploy/*"
          target: "/opt/myspringapp/"
          strip_components: 2

      - name: Restart docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            mkdir -p /opt/myspringapp/
            cd /opt/myspringapp/
            docker login registry.digitalocean.com -u paulbundy07@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
            yq -i '.services.user-service.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml   
            docker compose up -d --remove-orphans
