name: Deploy django app with docker

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-django-with-docker.yml'
      - 'mydjangoapp/**'
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      image_name: registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }}

    steps:
      - uses: actions/checkout@v4

      - name: Build and push docker
        working-directory: ./mydjangoapp
        run: |
          docker build -t registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }} .
          docker login registry.digitalocean.com -u paulbundy07@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
          docker push registry.digitalocean.com/my-registry123/mydjangoapp:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "./mydjangoapp/deploy/*"
          target: "/opt/mydjangoapp/"

      - name: Restart docker compose
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /opt/mydjangoapp/
            docker login registry.digitalocean.com -u paulbundy07@gmail.com -p ${{ secrets.REGISTRY_TOKEN }}
            yq -i '.services.web.image = "${{ needs.build.outputs.image_name }}"' docker-compose.yaml
            docker compose up -d --remove-orphans
            docker compose exec nginx nginx -s reload
