name: Deploy django app to server

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/deploy-django.yml'
      - 'mydjangoapp/**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: pip install packages
        working-directory: ./mydjangoapp
        run: |
          python3 -m venv env
          ./env/bin/pip install -r requirements.txt
          ./env/bin/pip show gunicorn
          ./env/bin/pip show django
          ls -lah ./env/lib

      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.DJANGO_SSH_HOST }}
          username: ${{ secrets.DJANGO_SSH_USERNAME }}
          key: ${{ secrets.DJANGO_SSH_KEY }}
          port: ${{ secrets.DJANGO_SSH_PORT }}
          source: "./mydjangoapp"
          target: "/opt/"

      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DJANGO_SSH_HOST }}
          username: ${{ secrets.DJANGO_SSH_USERNAME }}
          key: ${{ secrets.DJANGO_SSH_KEY }}
          port: ${{ secrets.DJANGO_SSH_PORT }}
          script: systemctl restart mydjangoapp-gunicorn